AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mufg-notification-lambda

  Sample SAM Template for mufg-notification-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Parameters:
  LineToken:
    Type: String
  S3Bucket:
    Type: String

Resources:
  MufgNotificationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: mufg_notification/
      Handler: app.handler
      Runtime: python3.7
      Events:
        S3PutEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: top_page
                  - Name: prefix
                    Value: product_page
      Environment:
        Variables:
          LINE_TOKEN: !Ref LineToken
          S3_BUCKET: !Ref S3Bucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket

#  Bs4Layer:
#    Type: AWS::Serverless::LayerVersion
#    Properties:
#      ContentUri: bs4
#      CompatibleRuntimes:
#        - python3.7
#    Metadata:
#      BuildMethod: python3.7
